name: Build Wrapper

on:
  push:
    paths:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, Win32]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        run: cmake -B build -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release --target win-capture-audio-wrapper
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-capture-audio-wrapper-${{ matrix.arch }}
          path: build/Release/win-capture-audio-wrapper.dll
